### ISSUE TITLE
Destaques escolhidos manualmente

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/portal-de-servicos#155]
- [x] 9 serviços listados (por ID) no `application.yaml`

Jogar um erro caso a lista tenha menos de 9 serviços.

**Comment by cv** [comment]
Estes destaques vão sobrescrever a ordem de quaisquer destaques escolhidos automaticamente pela #155.

Então,

- Caso o `application.yaml` liste 9 destaques, use-os
- Caso o `application.yaml` liste menos de 9 destaques, preencha o restante da lista com destaques vindos da #155.

Se/quando resolvermos que os destaques manuais não são mais interessantes, basta deixar a lista vazia e a aplicação deve se comportar corretamente (pegando os serviços mais acessados como destaque).

**Comment by erickpintor** [comment]
Uma nova entrada de configuração foi adicionada ao ```application.yaml``` afim de definir os serviços em destaque.

Os ```IDs``` dos serviços deve ser colocados na entrada ```gds.destaques.servicos```. Por exemplo:

```yaml
gds:
  destaques:
    servicos:
      - retificadora-on-line-extrato-da-dirpf
      - aposentadoria-por-invalidez
      - vistas-de-processo
```

Os 3 primeiros serviços em nosso ambiente de alpha já estão vindo desta nova configuração.
